#!/usr/bin/env python3
"""Render concise Markdown views from the JSON evidence ledger."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
CATALOG = ROOT / "catalog"
GENERATED = "<!-- Generated by scripts/render.py; edit data/*.json instead. -->\n"

LABEL = {
    "shortlist": "优先审核",
    "incubate": "孵化",
    "watch": "观察",
    "quarantine": "隔离",
    "proof_assistant": "证明助手",
    "executable_spec": "精确可执行验证",
    "precise_informal": "精确自然语言",
    "research_program": "研究计划",
}


def load(name: str) -> dict:
    return json.loads((DATA / name).read_text(encoding="utf-8"))


def esc(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def link(label: str, url: str) -> str:
    return f"[{esc(label)}]({url})"


def vector(problem: dict) -> str:
    fit = problem["fit"]
    order = [
        ("验", "verifiability"),
        ("馈", "feedback_richness"),
        ("表", "representation"),
        ("拆", "decomposability"),
        ("具", "tool_readiness"),
        ("部", "partial_value"),
        ("值", "math_value"),
        ("态", "status_confidence"),
        ("资", "resource_feasibility"),
    ]
    return " ".join(f"{short}{fit[key]}" for short, key in order)


def problem_table(items: list[dict]) -> str:
    rows = [
        "| 问题 | 决策 | 本轮冻结目标 | 终检 | 最大风险 |",
        "|---|---|---|---|---|",
    ]
    for item in items:
        rows.append(
            "| "
            + " | ".join(
                [
                    link(item["title_zh"], item["source"]["canonical_url"]),
                    LABEL[item["recommendation"]],
                    esc(item["statement"]["target_zh"]),
                    esc(item["verification"]["mode"]),
                    esc(item["risks_zh"][0]),
                ]
            )
            + " |"
        )
    return "\n".join(rows)


def render_shortlist(problems: list[dict], as_of: str) -> str:
    items = [p for p in problems if p["recommendation"] == "shortlist"]
    return GENERATED + f"""# 优先审核清单

状态日期：{as_of}。这里的“优先审核”不是“已经开放攻击”：在题意忠实度、最新文献和 evaluator 红队完成前，不晋升到 `active`。

{problem_table(items)}

维度不求和；完整理由和风险见 [问题卡](problem-cards.md)。
"""


def render_machine(problems: list[dict], as_of: str) -> str:
    items = [p for p in problems if p["formalization"]["level"] == "proof_assistant"]
    body = GENERATED + f"""# 已有明确 proof-assistant 形式化

状态日期：{as_of}。这里的“已形式化”仅指固定 revision 中存在完整目标陈述；它不保证译文忠实、问题仍开放，更不表示已有解答。`formal_status` 与“statement formalized”是不同概念。

{problem_table(items)}

| 问题 | 系统 | 固定声明 | fidelity | 九维向量（0–3） |
|---|---|---|---|---|
"""
    rows = []
    for item in items:
        f = item["formalization"]
        rows.append(
            f"| {esc(item['id'])} | {esc(f['system'])} | "
            f"{link(f['declaration'], f['artifact_url'])} | {esc(f['fidelity'])} | `{vector(item)}` |"
        )
    return body + "\n".join(rows) + "\n"


def render_nonmachine(problems: list[dict], as_of: str) -> str:
    items = [p for p in problems if p["formalization"]["level"] != "proof_assistant"]
    exact = [p for p in items if p["formalization"]["level"] == "executable_spec"]
    informal = [p for p in items if p["formalization"]["level"] != "executable_spec"]
    return GENERATED + f"""# 尚无完整 proof-assistant 形式化

状态日期：{as_of}。此栏继续区分“有限输出可精确验证”和“仍需 CAS/专家审核”；前者也不能被写成 Lean/Coq 已形式化。

## 精确可执行验证

{problem_table(exact)}

## 精确自然语言、尚需较重人工审核

{problem_table(informal)}
"""


def render_cards(problems: list[dict], as_of: str) -> str:
    chunks = [
        GENERATED.rstrip(),
        "# 问题卡",
        "",
        f"状态日期：{as_of}。九维顺序：可验证性、反馈密度、表示紧凑性、可拆分性、工具成熟度、部分进展价值、数学价值、状态可信度、资源可行性。分数只作向量，不求和。",
        "",
    ]
    for item in problems:
        formal = item["formalization"]
        gates = "；".join(f"{k}={v}" for k, v in item["hard_gates"].items())
        chunks.extend(
            [
                f"## {item['title_zh']}",
                "",
                f"- ID / 决策：`{item['id']}` / {LABEL[item['recommendation']]}",
                f"- 来源状态：{item['source']['source_label']}；可信度 {item['source']['status_confidence']}；{item['source']['checked_at']} 核查",
                f"- 形式化强度：{LABEL[formal['level']]}；fidelity `{formal['fidelity']}`",
                f"- 目标：{item['statement']['target_zh']}",
                f"- 成功工件：{item['statement']['success_artifact_zh']}",
                f"- 有价值的部分进展：{item['statement']['partial_progress_zh']}",
                f"- 验证：`{item['verification']['mode']}` — {item['verification']['notes_zh']}",
                f"- 硬门槛：`{gates}`",
                f"- 九维向量：`{vector(item)}`",
                f"- 风险：{'；'.join(item['risks_zh'])}",
                f"- 选择判断：{item['selection_note_zh']}",
                "",
            ]
        )
    return "\n".join(chunks).rstrip() + "\n"


def render_collections(source_data: dict) -> str:
    rows = [
        GENERATED.rstrip(),
        "# 题源与采集策略",
        "",
        f"状态日期：{source_data['as_of']}。整库进入 raw 层不代表整库进入精选层。",
        "",
        "| 题源 | 优先级 | 采集 | 项目中的角色 | 快照 |",
        "|---|---:|---|---|---|",
    ]
    for item in source_data["collections"]:
        rows.append(
            f"| {link(item['name'], item['canonical_url'])} | {esc(item['priority'])} | "
            f"{esc(item['ingestion'])} | {esc(item['trust_role'])} | `{esc(item['snapshot_revision'])}` |"
        )
    return "\n".join(rows) + "\n"


def render_evidence(data: dict) -> str:
    rows = [
        GENERATED.rstrip(),
        "# 选择标准的实证依据",
        "",
        f"状态日期：{data['as_of']}。这些案例用于推导任务形态，不用成功个案外推总体成功率。",
        "",
        "| 案例 | 观察 | 对选题的含义 | 不能忽略的限制 |",
        "|---|---|---|---|",
    ]
    for item in data["precedents"]:
        rows.append(
            f"| {link(item['name'], item['url'])} | {esc(item['observed_capability'])} | "
            f"{esc(item['selection_implication'])} | {esc(item['caveat'])} |"
        )
    return "\n".join(rows) + "\n"


def render_quarantine(data: dict) -> str:
    rows = [
        GENERATED.rstrip(),
        "# 隔离与反例",
        "",
        f"状态日期：{data['as_of']}。隔离项展示为什么“数据库写 open”或“已有 Lean 文件”都不够。",
        "",
        "| 项目 | 当前状态 | 原因 | 下次检查 |",
        "|---|---|---|---|",
    ]
    for item in data["items"]:
        rows.append(
            f"| {esc(item['title'])} | `{esc(item['state'])}` | {esc(item['reason'])} | {esc(item['recheck_after'])} |"
        )
    return "\n".join(rows) + "\n"


def outputs() -> dict[Path, str]:
    problem_data = load("problems.json")
    source_data = load("sources.json")
    precedent_data = load("precedents.json")
    quarantine_data = load("quarantine.json")
    problems = problem_data["problems"]
    return {
        CATALOG / "shortlist.md": render_shortlist(problems, problem_data["as_of"]),
        CATALOG / "machine-formalized.md": render_machine(problems, problem_data["as_of"]),
        CATALOG / "not-machine-formalized.md": render_nonmachine(problems, problem_data["as_of"]),
        CATALOG / "problem-cards.md": render_cards(problems, problem_data["as_of"]),
        CATALOG / "collections.md": render_collections(source_data),
        CATALOG / "evidence.md": render_evidence(precedent_data),
        CATALOG / "quarantine.md": render_quarantine(quarantine_data),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()
    stale: list[Path] = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"rendered {path.relative_to(ROOT)}")
    if stale:
        print("generated files are stale: " + ", ".join(str(p.relative_to(ROOT)) for p in stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
